---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
Page:
  extensions:
    - PublicationPage
PageController:
  extensions:
    - PublicationPage_Controller
Article:
  extensions:
    - ArticleWordExtension
BlogPost:
  extensions:
    - BlogPostExtension
VersionTruncator:
  version_limit: 1
  draft_limit: 1
  delete_old_page_types: false
  vacuum_tables: false
SilverStripe\View\SSViewer:
  rewrite_hash_links: false
  themes:
    - '$public'
    - 'jgrj'
    - 'md/publication-project'
    - '$default'
SilverStripe\Assets\Flysystem\AssetAdapter:
  file_permissions:
    'file':
      'public': '0644'
      'private': '0600'