---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
Page:
  extensions:
    - PublicationPage
PageController:
  extensions:
    - PublicationPage_Controller
Article:
  extensions:
    - ArticleWordExtension
VersionTruncator:
  version_limit: 1
  draft_limit: 1
  delete_old_page_types: false
  vacuum_tables: false
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'jgrj'
    - 'md/publication-project'
    - '$default'
